# Generated by Django 4.0.9 on 2023-02-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_last_accessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publishers',
        ),
    ]
