# Generated by Django 4.0.9 on 2023-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_person_age_person_email_person_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('男', 'man'), ('女', 'woman')], default='', max_length=50, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='text',
            field=models.TextField(default='default text', verbose_name='内容'),
        ),
    ]
