# Generated by Django 4.0.9 on 2023-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_animal_alter_restaurant_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
